services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    # volumes:
    #   - ./prisma/dev.db:/usr/src/app/prisma/dev.db
    restart: unless-stopped
